version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: 'nest'
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 6500:5432
    networks:
      - nest-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge
